// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.netty.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 2;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
