// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.netty.proto;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_PersonResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_PersonResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_PersonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_proto_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\017com.netty.proto\"%\n\rStrea" +
      "mRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016Stream" +
      "Response\022\025\n\rresponse_info\030\001 \001(\t\"Q\n\022Perso" +
      "nResponseList\022;\n\022PersonResponseList\030\001 \003(" +
      "\0132\037.com.netty.proto.PersonResponse\"\034\n\rPe" +
      "rsonRequest\022\013\n\003age\030\001 \001(\005\"<\n\016PersonRespon" +
      "se\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007address" +
      "\030\003 \001(\t\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n" +
      "\nMyResponse\022\020\n\010realName\030\002 \001(\t2\356\002\n\rPerson" +
      "Service\022R\n\025getRealNameByUserName\022\032.com.n" +
      "etty.proto.MyRequest\032\033.com.netty.proto.M" +
      "yResponse\"\000\022U\n\016getPersonByAge\022\036.com.nett" +
      "y.proto.PersonRequest\032\037.com.netty.proto." +
      "PersonResponse\"\0000\001\022a\n\026getPersonWrapperBy" +
      "Ages\022\036.com.netty.proto.PersonRequest\032#.c" +
      "om.netty.proto.PersonResponseList\"\000(\001\022O\n" +
      "\006biTalk\022\036.com.netty.proto.StreamRequest\032" +
      "\037.com.netty.proto.StreamResponse\"\000(\0010\001B\"" +
      "\n\017com.netty.protoB\013PersonProtoH\001P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_netty_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_netty_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netty_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
    internal_static_com_netty_proto_PersonResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_netty_proto_PersonResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_PersonResponseList_descriptor,
        new java.lang.String[] { "PersonResponseList", });
    internal_static_com_netty_proto_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_netty_proto_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_PersonRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_netty_proto_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_netty_proto_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_PersonResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_com_netty_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_netty_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_netty_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_netty_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_proto_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
