// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.netty.proto;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.proto.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
