// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.netty.proto;

public interface PersonResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.proto.PersonResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.netty.proto.PersonResponse PersonResponseList = 1;</code>
   */
  java.util.List<com.netty.proto.PersonResponse> 
      getPersonResponseListList();
  /**
   * <code>repeated .com.netty.proto.PersonResponse PersonResponseList = 1;</code>
   */
  com.netty.proto.PersonResponse getPersonResponseList(int index);
  /**
   * <code>repeated .com.netty.proto.PersonResponse PersonResponseList = 1;</code>
   */
  int getPersonResponseListCount();
  /**
   * <code>repeated .com.netty.proto.PersonResponse PersonResponseList = 1;</code>
   */
  java.util.List<? extends com.netty.proto.PersonResponseOrBuilder> 
      getPersonResponseListOrBuilderList();
  /**
   * <code>repeated .com.netty.proto.PersonResponse PersonResponseList = 1;</code>
   */
  com.netty.proto.PersonResponseOrBuilder getPersonResponseListOrBuilder(
      int index);
}
