// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.netty.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
